name: Cursor Agent
description: Run Cursor CLI on @cursor mentions
inputs:
  cursor_api_key:
    required: true
  gitea_token:
    required: true
  gitea_base_url:
    required: true

runs:
  using: composite
  steps:
    - run: |
        echo "${{ gitea.event.comment.body }}" > comment.txt
        if ! grep -q "@cursor" comment.txt; then
          echo "No @cursor mention – exiting."
          exit 0
        fi
      shell: bash

    - name: Download Gitea MCP Server
      shell: bash
      run: |
        set -e

        MCP_DIR="/tmp/gitea-mcp"
        MCP_TAR="gitea-mcp.tar.gz"
        MCP_URL="https://gitea.com/gitea/gitea-mcp/releases/download/v0.7.0/gitea-mcp_Linux_x86_64.tar.gz"

        mkdir -p "$MCP_DIR"
        cd "$MCP_DIR"

        echo "Downloading Gitea MCP Server..."
        curl -L "$MCP_URL" -o "$MCP_TAR"

        echo "Extracting..."
        tar -xzf "$MCP_TAR"

        echo "Making binary executable..."
        chmod +x gitea-mcp

        echo "Gitea MCP Server ready at $MCP_DIR/gitea-mcp"

    - name: Run Cursor
      shell: bash
      env:
        CURSOR_API_KEY: ${{ inputs.cursor_api_key }}
        GITEA_ACCESS_TOKEN: ${{ inputs.gitea_token }}
        GITEA_BASE_URL: ${{ inputs.gitea_base_url }}
        GITEA_MCP_PATH: /tmp/gitea-mcp/gitea-mcp
      run: |
        ./scripts/run-cursor.sh